Document: libinchi1
Title: Debian libinchi1 Manual
Author: <insert document author here>
Abstract: This manual describes what libinchi1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libinchi1/libinchi1.sgml.gz

Format: postscript
Files: /usr/share/doc/libinchi1/libinchi1.ps.gz

Format: text
Files: /usr/share/doc/libinchi1/libinchi1.text.gz

Format: HTML
Index: /usr/share/doc/libinchi1/html/index.html
Files: /usr/share/doc/libinchi1/html/*.html
